language: dart
dart:
  # Install the latest stable release
  - stable
services:
  - docker
before_install:
  - docker run --rm -it -p 8000:8000 -p 8080:8080 -p 9080:9080 dgraph/standalone:latest
notifications:
  email: false